### PR TITLE
AE-0016 - Project Refactor 2.0

### LINKED ISSUE #23: [BUG] Cannot save diagram in current build
**Describe the bug**
When creating a diagram, it is currently not possible to save the diagram and reload it back into the application

**To Reproduce**
1. Open the program
2. Click new project
3. Add some components and gates within them if you wish
4. Either use Ctrl+S or the save option in the file menu to save the file

**Expected behavior**
The file will be created with a .aea file extension

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux (Fedora)
 - JDK Version: 13

### PR DESCRIPTION
**Pull request by RyanShoobert**
Addresses #24 
Also appears to have fixed #23

### CODE REVIEW

File: src/main/java/configuration/javafx/TabWrapper.java [hunk 1]
```diff
@@ -48,28 +45,23 @@ public void addTab() {
...
                 this.logger.log(Level.INFO, "Diagram tab refreshed");
             });
 
-            tab.setText(diagram.getName());
+            tab.setText("diagram.getName()");
 
             this.tabPane.getTabs().add(tab);
         } catch (IOException exception) {
-            logger.log(Level.INFO, "Could not create tab for models: {0}", diagram);
+            logger.log(Level.INFO, "Could not create tab for models: {0}", "diagram");
```
Comment (RyanShoobert) [inline src/main/java/configuration/javafx/TabWrapper.java:60]: Will need to change these to actual names at some point
