### PR TITLE
AE-0013 - Fixed state sync bug

### LINKED ISSUE #16: [BUG] Component state reset when new Component added in Diagram View
An issue was discovered during testing where component state appears to be reset when a new component is added after modification. 

Steps to reproduce:
1.  Add component in DiagramView
2. Enter ComponentView for that component and add some logic gate
3. Exit and renter to verify they are there
4. Add another Component and then re-enter original one
5. You will see that the logic gates are no longer there

### PR DESCRIPTION
**Pull request by RyanShoobert**
Fixes #16

### CODE REVIEW

File: src/main/java/configuration/javafx/TabWrapper.java [hunk 1]
```diff
@@ -58,7 +58,8 @@ public void addTab() {
                 this.logger.log(Level.INFO, "Diagram tab refreshed");
             });
 
-            tab.setText(diagram.getDiagramName());
+            tab.setText(diagram.getName());
```
Comment (RyanShoobert) [inline src/main/java/configuration/javafx/TabWrapper.java:61]: Check this functions correctly after merge
